import './globals.css'
import { DM_Serif_Display} from 'next/font/google'

const dmSerifDisplay = DM_Serif_Display({ subsets: ["latin"], weight: "400" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dmSerifDisplay.className}>{children}</body>
    </html>
  )
}
